create table public.daily_chemical_status (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  date text not null,
  status text not null default 'pending'::text,
  notes text null,
  confirmed_at timestamp with time zone null,
  created_at timestamp with time zone not null default timezone ('Asia/Ho_Chi_Minh'::text, now()),
  updated_at timestamp with time zone null default timezone ('Asia/Ho_Chi_Minh'::text, now()),
  date_type text null default 'single'::text,
  start_date date null,
  end_date date null,
  constraint daily_chemical_status_pkey primary key (id),
  constraint daily_chemical_status_user_date_unique unique (user_id, date),
  constraint daily_chemical_status_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists daily_chemical_status_user_date_idx on public.daily_chemical_status using btree (user_id, date) TABLESPACE pg_default;

create index IF not exists daily_chemical_status_date_range_idx on public.daily_chemical_status using btree (start_date, end_date) TABLESPACE pg_default;