create table public.job_assignments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  technician_id uuid not null,
  assigned_at timestamp with time zone not null default now(),
  status text not null default 'assigned'::text,
  notes text null,
  role text null default 'member'::text,
  job_id uuid null,
  constraint job_assignments_pkey primary key (id),
  constraint job_assignments_job_id_fkey foreign KEY (job_id) references jobs (id) on delete CASCADE,
  constraint job_assignments_technician_id_fkey foreign KEY (technician_id) references technicians (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists job_assignments_technician_id_idx on public.job_assignments using btree (technician_id) TABLESPACE pg_default;

create index IF not exists job_assignments_role_idx on public.job_assignments using btree (role) TABLESPACE pg_default;