create table public.job_report_images (
  id bigint generated by default as identity not null,
  report_id bigint not null,
  image_url text not null,
  created_at timestamp with time zone not null default now(),
  noted text null,
  constraint job_report_images_pkey primary key (id),
  constraint job_report_images_report_id_fkey foreign KEY (report_id) references job_reports (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists job_report_images_report_id_idx on public.job_report_images using btree (report_id) TABLESPACE pg_default;