create table public.job_materials (
  id bigint generated by default as identity not null,
  material_id uuid not null,
  required_quantity numeric(10, 2) not null default 0,
  actual_quantity numeric(10, 2) null default 0,
  notes text null,
  created_at timestamp with time zone not null default timezone ('Asia/Ho_Chi_Minh'::text, now()),
  job_id uuid null,
  constraint job_materials_pkey primary key (id),
  constraint job_materials_job_id_fkey foreign KEY (job_id) references jobs (id) on delete CASCADE,
  constraint job_materials_material_id_fkey foreign KEY (material_id) references materials (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists job_materials_material_id_idx on public.job_materials using btree (material_id) TABLESPACE pg_default;