create table public.job_reports (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  check_in_time timestamp with time zone null,
  check_out_time timestamp with time zone null,
  notes text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  job_id uuid null,
  constraint work_reports_pkey primary key (id),
  constraint work_reports_job_id_fkey foreign KEY (job_id) references jobs (id) on delete CASCADE,
  constraint work_reports_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create unique INDEX IF not exists uidx_work_reports_job_id on public.job_reports using btree (job_id) TABLESPACE pg_default;

create index IF not exists idx_work_reports_created_at on public.job_reports using btree (created_at) TABLESPACE pg_default;

create index IF not exists work_reports_user_id_idx on public.job_reports using btree (user_id) TABLESPACE pg_default;