create table public.work_reports (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  user_email text null,
  check_in_time timestamp with time zone null,
  check_out_time timestamp with time zone null,
  notes text null,
  created_at timestamp with time zone not null default timezone ('Asia/Ho_Chi_Minh'::text, now()),
  updated_at timestamp with time zone null default timezone ('Asia/Ho_Chi_Minh'::text, now()),
  job_id uuid null,
  constraint work_reports_pkey primary key (id),
  constraint work_reports_job_id_fkey foreign KEY (job_id) references jobs (id) on delete CASCADE,
  constraint work_reports_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists work_reports_user_id_idx on public.work_reports using btree (user_id) TABLESPACE pg_default;