-- Bảng cho hóa chất/vật tư
CREATE TABLE public.materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  unit text NOT NULL DEFAULT 'lít',
  category text NULL DEFAULT 'hóa chất',
  notes text NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NULL DEFAULT timezone('Asia/Ho_Chi_Minh'::text, now()),
  CONSTRAINT materials_pkey PRIMARY KEY (id),
  CONSTRAINT materials_name_key UNIQUE (name)
) TABLESPACE pg_default;

-- Bảng liên kết công việc với hóa chất yêu cầu
CREATE TABLE public.job_materials (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  job_id bigint NOT NULL,
  material_id uuid NOT NULL,
  required_quantity numeric(10,2) NOT NULL DEFAULT 0,
  actual_quantity numeric(10,2) NULL DEFAULT 0,
  notes text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('Asia/Ho_Chi_Minh'::text, now()),
  CONSTRAINT job_materials_pkey PRIMARY KEY (id),
  CONSTRAINT job_materials_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE,
  CONSTRAINT job_materials_material_id_fkey FOREIGN KEY (material_id) REFERENCES materials (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- Bảng cho checklist đã hoàn thành
CREATE TABLE public.job_checklist_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  job_id bigint NOT NULL,
  checklist_id uuid NOT NULL,
  completed boolean NOT NULL DEFAULT false,
  notes text NULL,
  completed_at timestamp with time zone NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('Asia/Ho_Chi_Minh'::text, now()),
  CONSTRAINT job_checklist_items_pkey PRIMARY KEY (id),
  CONSTRAINT job_checklist_items_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE,
  CONSTRAINT job_checklist_items_checklist_id_fkey FOREIGN KEY (checklist_id) REFERENCES checklist (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- Bảng trạng thái hóa chất hàng ngày
CREATE TABLE public.daily_chemical_status (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  date date NOT NULL,
  status text NOT NULL DEFAULT 'pending', -- 'pending', 'confirmed'
  notes text NULL,
  confirmed_at timestamp with time zone NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('Asia/Ho_Chi_Minh'::text, now()),
  updated_at timestamp with time zone NULL DEFAULT timezone('Asia/Ho_Chi_Minh'::text, now()),
  CONSTRAINT daily_chemical_status_pkey PRIMARY KEY (id),
  CONSTRAINT daily_chemical_status_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT daily_chemical_status_user_date_unique UNIQUE (user_id, date)
) TABLESPACE pg_default;

-- Thêm trường vào bảng jobs
ALTER TABLE public.jobs 
ADD COLUMN IF NOT EXISTS scheduled_time text,
ADD COLUMN IF NOT EXISTS contact_person text,
ADD COLUMN IF NOT EXISTS contact_phone text,
ADD COLUMN IF NOT EXISTS special_requests text,
ADD COLUMN IF NOT EXISTS address text;

-- Indexes
CREATE INDEX IF NOT EXISTS job_materials_job_id_idx ON public.job_materials USING btree (job_id);
CREATE INDEX IF NOT EXISTS job_materials_material_id_idx ON public.job_materials USING btree (material_id);
CREATE INDEX IF NOT EXISTS job_checklist_items_job_id_idx ON public.job_checklist_items USING btree (job_id);
CREATE INDEX IF NOT EXISTS daily_chemical_status_user_date_idx ON public.daily_chemical_status USING btree (user_id, date);
