-- Script tạo lại bảng daily_chemical_status (nếu cần)
DROP TABLE IF EXISTS public.daily_chemical_status CASCADE;

CREATE TABLE public.daily_chemical_status (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  date text NOT NULL, -- Cho phép cả single date và range như "2025-08-15" hoặc "2025-08-15_2025-08-18"
  status text NOT NULL DEFAULT 'pending', -- 'pending', 'confirmed'
  notes text NULL,
  confirmed_at timestamp with time zone NULL,
  date_type text DEFAULT 'single', -- 'single' hoặc 'range'
  start_date date NULL, -- Ngày bắt đầu
  end_date date NULL, -- Ngày kết thúc
  created_at timestamp with time zone NOT NULL DEFAULT timezone('Asia/Ho_Chi_Minh'::text, now()),
  updated_at timestamp with time zone NULL DEFAULT timezone('Asia/Ho_Chi_Minh'::text, now()),
  CONSTRAINT daily_chemical_status_pkey PRIMARY KEY (id),
  CONSTRAINT daily_chemical_status_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT daily_chemical_status_user_date_unique UNIQUE (user_id, date)
) TABLESPACE pg_default;

-- Indexes
CREATE INDEX daily_chemical_status_user_date_idx ON public.daily_chemical_status USING btree (user_id, date);
CREATE INDEX daily_chemical_status_date_range_idx ON public.daily_chemical_status USING btree (start_date, end_date);
